'use client';
import { useEffect,useMemo,useState } from 'react';
type Service={id:string;slug:string;name:string;priceType:string;priceMin:number|null;priceMax:number|null;durationMinutes:number|null;depositType:string;depositValue:number|null;category:{slug:string;name:string};artists:{artist:{id:string;displayName:string;roleLabels:string[]}}[];options:{id:string;name:string;description:string|null;priceDelta:number;durationDelta:number;required:boolean;active:boolean}[]};
const steps=['Area','Category','Service','Artist','Options','Time','Your details','Review','Policies'];
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
export default function BookingFlow({services,policies,initialSlug}:{services:Service[];policies:{title:string;body:string}[];initialSlug?:string}){
  const initial=services.find(s=>s.slug===initialSlug);
  const [step,setStep]=useState(initial?3:0),[area,setArea]=useState(initial?.category.slug==='esthetics'?'Esthetics':'Hair'),[category,setCategory]=useState(initial?.category.slug||''),[serviceId,setServiceId]=useState(initial?.id||''),[artistId,setArtistId]=useState(initial?.artists[0]?.artist.id||''),[optionIds,setOptionIds]=useState<string[]>([]),[date,setDate]=useState(''),[time,setTime]=useState(''),[slots,setSlots]=useState<string[]>([]),[loadingSlots,setLoadingSlots]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[notes,setNotes]=useState(''),[accepted,setAccepted]=useState(false),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false),[reference,setReference]=useState(''),[appointmentId,setAppointmentId]=useState(''),[depositDue,setDepositDue]=useState(0);
  const service=services.find(s=>s.id===serviceId);const categories=useMemo(()=>[...new Set(services.filter(s=>area==='Esthetics'?s.category.slug==='esthetics':s.category.slug!=='esthetics').map(s=>s.category.slug))], [area,services]);
  useEffect(()=>{if(!date||!serviceId||!artistId)return;let alive=true;setLoadingSlots(true);setTime('');fetch(`/api/slots?serviceId=${encodeURIComponent(serviceId)}&artistId=${encodeURIComponent(artistId)}&date=${date}&optionIds=${encodeURIComponent(optionIds.join(','))}`).then(r=>r.json()).then(data=>{if(alive)setSlots(data.slots||[])}).catch(()=>{if(alive)setSlots([])}).finally(()=>{if(alive)setLoadingSlots(false)});return()=>{alive=false}},[date,serviceId,artistId,optionIds]);
  const optionPrice=service?.options.filter(o=>optionIds.includes(o.id)).reduce((n,o)=>n+o.priceDelta,0)||0;const estimated=service?.priceMin==null?null:service.priceMin+optionPrice;const deposit=service?.depositType==='FLAT'?Math.min(estimated||0,service.depositValue||0):service?.depositType==='PERCENT'?Math.round((estimated||0)*(service.depositValue||0)/100):0;
  function next(){setError('');if(step===2&&!serviceId)return setError('Choose a service.');if(step===3&&!artistId)return setError('Choose an artist.');if(step===5&&(!date||!time))return setError('Choose a date and time.');if(step===6&&(!name.trim()||!email.includes('@')))return setError('Enter your name and email.');if(step===8&&!accepted)return setError('Please accept the published policies to continue.');setStep(Math.min(step+1,8));}
  async function submit(){if(!accepted)return setError('Please accept the policies.');setSubmitting(true);setError('');try{const response=await fetch('/api/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serviceId,artistId,date,time,name,email,phone,notes,optionIds,accepted,website:''})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Booking failed');setReference(data.reference);setAppointmentId(data.appointmentId);setDepositDue(data.depositDue)}catch(e){setError(e instanceof Error?e.message:'Booking failed. Please try again.')}finally{setSubmitting(false)}}
  async function pay(){setSubmitting(true);setError('');try{const response=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appointmentId,reference})});const data=await response.json();if(!response.ok)throw new Error(data.error);window.location.assign(data.url)}catch(e){setError(e instanceof Error?e.message:'Checkout unavailable')}finally{setSubmitting(false)}}
  if(reference)return <div className="empty-state"><p className="eyebrow">Appointment request received</p><h2 style={{fontSize:'3rem'}}>You&apos;re on your way.</h2><p>Your reference is <strong>{reference}</strong>.</p>{depositDue>0?<><p>A deposit of {money(depositDue)} is required to confirm your appointment.</p><button className="button button-dark" disabled={submitting} onClick={pay}>Pay deposit securely ↗</button></>:<p>Your appointment is confirmed. We&apos;ll send the details to {email} when email delivery is configured.</p>}{error&&<p role="alert" className="notice">{error}</p>}</div>;
  return <div><div className="steps" aria-label="Booking progress">{steps.map((label,i)=><span className={`step ${i<=step?'active':''}`} key={label}>{i+1}. {label}</span>)}</div><p className="eyebrow">Step {step+1} of {steps.length}</p><h2 style={{fontSize:'clamp(2.5rem,5vw,4rem)'}}>{['What are you here for?','Choose a category.','Choose your service.','Meet your artist.','Make it yours.','Find a time.','Your details.','Review your visit.','Studio policies.'][step]}</h2>
    {step===0&&<div className="choice-grid">{['Hair','Esthetics'].map(value=><button className={`choice ${area===value?'selected':''}`} key={value} onClick={()=>{setArea(value);setCategory('');setServiceId('');setArtistId('')}}><strong>{value}</strong><span>{value==='Hair'?'Braids, natural hair, and locs':'Esthetic care'}</span></button>)}</div>}
    {step===1&&<div className="choice-grid">{categories.map(slug=><button className={`choice ${category===slug?'selected':''}`} key={slug} onClick={()=>{setCategory(slug);setServiceId('');setArtistId('')}}><strong>{services.find(s=>s.category.slug===slug)?.category.name}</strong></button>)}</div>}
    {step===2&&<div className="choice-grid">{services.filter(s=>s.category.slug===category).map(s=><button className={`choice ${serviceId===s.id?'selected':''}`} key={s.id} onClick={()=>{setServiceId(s.id);setArtistId(s.artists.length===1?s.artists[0].artist.id:'');setOptionIds(s.options.filter(o=>o.required).map(o=>o.id));setDate('')}}><strong>{s.name}</strong><span>{s.priceMin==null?'Price varies':s.priceType==='STARTING'?`Starting at ${money(s.priceMin)}`:money(s.priceMin)}{s.durationMinutes?` · ${s.durationMinutes} min`:''}</span></button>)}</div>}
    {step===3&&<div className="choice-grid">{service?.artists.map(({artist})=><button className={`choice ${artistId===artist.id?'selected':''}`} key={artist.id} onClick={()=>{setArtistId(artist.id);setDate('')}}><strong>{artist.displayName}</strong><span>{artist.roleLabels.join(' + ')}</span></button>)}</div>}
    {step===4&&<div>{service?.options.filter(o=>o.active).length?<div className="choice-grid">{service.options.filter(o=>o.active).map(o=><label className="choice" key={o.id}><input type="checkbox" checked={optionIds.includes(o.id)} disabled={o.required} onChange={()=>setOptionIds(current=>current.includes(o.id)?current.filter(id=>id!==o.id):[...current,o.id])}/> <strong>{o.name}{o.required?' (included)':''}</strong><span>{o.description}{o.priceDelta?` · +${money(o.priceDelta)}`:''}</span></label>)}</div>:<p className="notice">This service has no additional options.</p>}</div>}
    {step===5&&<div><div className="field"><label htmlFor="date">Appointment date</label><input id="date" type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></div>{loadingSlots?<p role="status">Finding available times…</p>:date&&<>{slots.length?<div className="slot-grid">{slots.map(slot=><button key={slot} className={`slot ${time===slot?'selected':''}`} onClick={()=>setTime(slot)}>{slot}</button>)}</div>:<p className="notice">No times are available on this date. Try another day.</p>}</>}</div>}
    {step===6&&<div className="form-grid"><div className="field"><label htmlFor="name">Full name *</label><input id="name" autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label htmlFor="email">Email *</label><input id="email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label htmlFor="phone">Phone</label><input id="phone" type="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="field full"><label htmlFor="notes">Anything your artist should know? (optional)</label><textarea id="notes" value={notes} onChange={e=>setNotes(e.target.value)}/></div></div>}
    {step===7&&<div className="service-card"><p><strong>Service</strong><br/>{service?.name}</p><p><strong>Artist</strong><br/>{service?.artists.find(a=>a.artist.id===artistId)?.artist.displayName}</p><p><strong>When</strong><br/>{date} at {time} (New York time)</p><p><strong>Estimate</strong><br/>{estimated==null?'Price varies':service?.priceType==='STARTING'?`Starting at ${money(estimated)}`:money(estimated)}</p><p><strong>Deposit due now</strong><br/>{money(deposit)}</p>{estimated!=null&&<p><strong>Estimated balance</strong><br/>{money(estimated-deposit)}</p>}<p className="muted">Final service pricing may vary when a starting price or range is shown.</p></div>}
    {step===8&&<div className="stack">{policies.length?policies.map(p=><details className="service-card" key={p.title}><summary>{p.title}</summary><p style={{whiteSpace:'pre-wrap'}}>{p.body}</p></details>):<p className="notice">No studio policies have been published yet.</p>}<label className="choice"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> I have reviewed the published policies and accept them for this appointment.</label></div>}
    {error&&<p role="alert" className="notice" style={{marginTop:20}}>{error}</p>}<div className="actions"><button className="button button-outline" type="button" disabled={step===0||submitting} onClick={()=>{setError('');setStep(step-1)}}>Back</button>{step<8?<button className="button button-dark" type="button" onClick={next}>Continue ↗</button>:<button className="button button-dark" type="button" disabled={submitting} onClick={submit}>{submitting?'Booking…':'Confirm appointment ↗'}</button>}</div></div>;
}
