import Image from 'next/image';
import Link from 'next/link';
import { getArtists,getCategories,getServices } from '@/lib/catalog';
import { content,priceLabel,setting } from '@/lib/site';
import { db } from '@/lib/db';

export default async function Home(){
  const [artists,categories,services,heroTitle,heroBody,introTitle,introBody,heroImage,heroCtas]=await Promise.all([getArtists(),getCategories(),getServices(),content('home.hero.title','Your Hair. Your Skin. Your Crown.'),content('home.hero.body','Natural Hair · Braids · Locs · Esthetics'),content('home.intro.title','Two artists. One lovely experience.'),content('home.intro.body','Professional hair care, protective styling, loc artistry, and esthetic care come together under one studio brand.'),setting('heroImage','/images/editorial-hero.png'),setting('heroCtas',{primary:{label:'Book an appointment',href:'/book'},secondary:{label:'Explore services',href:'/services'}})]);
  let gallery:{id:string;imageUrl:string|null;altText:string;caption:string|null}[]=[]; let testimonials:{id:string;displayName:string;text:string;rating:number}[]=[];let social:{id:string;mediaUrl:string;destinationUrl:string;altText:string;platform:string}[]=[];
  try{[gallery,testimonials,social]=await Promise.all([db.galleryItem.findMany({where:{published:true,featured:true},take:4,orderBy:{displayOrder:'asc'}}),db.testimonial.findMany({where:{status:'PUBLISHED',featured:true},take:3,orderBy:{createdAt:'desc'}}),db.socialPost.findMany({where:{published:true,featured:true},take:4,orderBy:{displayOrder:'asc'}})]);}catch{}
  return <><section className="hero"><Image className="hero-image" src={heroImage} alt="Editorial portrait celebrating natural hair and locs" fill priority sizes="100vw" unoptimized={heroImage.startsWith('http')}/><div className="container hero-content"><p className="eyebrow">MahLovely Studio</p><h1>{heroTitle}</h1><p>{heroBody}</p><p>Two artists. One lovely experience.</p><div className="hero-actions"><Link className="button button-dark" href={heroCtas.primary.href}>{heroCtas.primary.label} ?</Link><Link className="button button-outline" href={heroCtas.secondary.href}>{heroCtas.secondary.label}</Link></div></div></section>
  <section className="section"><div className="container intro-grid"><div><p className="eyebrow">The studio</p><h2>{introTitle}</h2></div><div className="intro-copy"><div className="rule"/><p>{introBody}</p><Link className="text-link" href="/about">Meet MahLovely ↗</Link></div></div></section>
  <section className="section dark-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">The people behind the artistry</p><h2>Meet your artists.</h2></div><Link className="text-link" href="/artists">View all artists ↗</Link></div><div className="artist-grid">{artists.map(a=><Link className={`artist-card${a.coverUrl?' artist-card-image':''}`} key={a.slug} href={`/artists/${a.slug}`} style={a.coverUrl?{backgroundImage:`linear-gradient(0deg,rgba(0,0,0,.7),transparent),url(${a.coverUrl})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}><p className="eyebrow">MahLovely artist</p><h3>{a.displayName}</h3><p>{a.roleLabels.join(' + ')}</p><p>{a.bio}</p><span className="text-link">Explore {a.displayName}&apos;s services ↗</span></Link>)}</div></div></section>
  <section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Made for your crown</p><h2>Find your service.</h2></div><Link className="text-link" href="/services">View full menu ↗</Link></div><div className="category-grid">{categories.map((c,i)=><Link className="category-card" key={c.slug} href={`/services?category=${c.slug}`}><p className="eyebrow">0{i+1} / {c.name}</p><div><h3>{c.name}</h3><p>{c.description}</p></div><span>↗</span></Link>)}</div></div></section>
  <section className="section" style={{background:'#eee8dd'}}><div className="container"><div className="section-heading"><div><p className="eyebrow">A place to begin</p><h2>Featured services.</h2></div></div><div className="service-grid">{services.filter(s=>s.featured).slice(0,6).map(s=><article className="service-card" key={s.slug}><p className="eyebrow">{s.category.name} · {s.artists.map(a=>a.artist.displayName).join(', ')}</p><h3><Link href={`/services/${s.slug}`}>{s.name}</Link></h3><p className="muted">{s.shortDescription || 'Care and styling tailored to your appointment.'}</p><div className="card-bottom"><strong>{priceLabel(s)}</strong><Link className="text-link" href={`/services/${s.slug}`}>Details ↗</Link></div></article>)}</div></div></section>
  {gallery.length>0&&<section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">The work</p><h2>Beautiful in every detail.</h2></div><Link className="text-link" href="/gallery">Explore gallery ↗</Link></div><div className="gallery-grid">{gallery.map(item=><figure className="gallery-item" key={item.id}>{item.imageUrl&&<Image src={item.imageUrl} alt={item.altText} width={600} height={700} unoptimized={item.imageUrl.startsWith('http')}/>}<figcaption className="gallery-caption">{item.caption}</figcaption></figure>)}</div></div></section>}
  {testimonials.length>0&&<section className="section"><div className="container"><p className="eyebrow">Kind words</p><h2>From the chair.</h2><div className="service-grid">{testimonials.map(t=><blockquote className="service-card" key={t.id}><p aria-label={`${t.rating} out of 5 stars`}>{'★'.repeat(t.rating)}</p><p>“{t.text}”</p><cite>— {t.displayName}</cite></blockquote>)}</div></div></section>}
  <section className="cta-band"><p className="eyebrow">Your next visit begins here</p><h2>Ready for your appointment?</h2><p>Book your next MahLovely experience.</p><Link className="button button-light" href="/book">Book now ↗</Link></section>{social.length>0&&<section className="section-tight social-band"><div className="container"><p className="eyebrow">Stay connected</p><h2>Follow the lovely.</h2><p>See the latest work and studio moments.</p><div className="gallery-grid">{social.map(post=><a className="gallery-item" key={post.id} href={post.destinationUrl} target="_blank" rel="noopener noreferrer"><Image src={post.mediaUrl} alt={post.altText} width={500} height={500} unoptimized={post.mediaUrl.startsWith('http')}/><span className="gallery-caption">{post.platform} ↗</span></a>)}</div></div></section>}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'BeautySalon',name:'MahLovely Studio',url:process.env.SITE_URL||'http://localhost:3000',image:`${process.env.SITE_URL||'http://localhost:3000'}/brand/mahlovely-logo.png`})}}/></>;
}
