import { NextRequest,NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { currentUser } from '@/lib/auth';
import { errorResponse,safeOrigin } from '@/lib/http';
import { acquireSlotLocks } from '@/lib/booking';
import type { BookingStatus, PaymentStatus, Prisma, PublishStatus } from '@prisma/client';
import { hash } from 'bcryptjs';
const allowed=['services','options','categories','artists','team','gallery','social','testimonials','content','policies','faqs','notifications','settings','clients','inquiries','appointments','availability','blockedTimes'];
type Input=Record<string,unknown>;
const str=(v:unknown)=>typeof v==='string'?v.trim():'';
const optional=(v:unknown)=>str(v)||null;
const num=(v:unknown)=>v===''||v==null?null:Number(v);
const arr=(v:unknown)=>str(v).split(',').map(s=>s.trim()).filter(Boolean);
const bool=(v:unknown)=>v===true;
async function authorize(req:NextRequest,section:string){if(!safeOrigin(req))throw new Error('Invalid origin');if(!allowed.includes(section))throw new Error('Unknown section');const user=await currentUser();if(!user||!['OWNER','ADMIN','ARTIST'].includes(user.role))throw new Error('Forbidden');if(section==='team'&&user.role!=='OWNER')throw new Error('Forbidden');if(user.role==='ARTIST'&&!['availability','blockedTimes','gallery','services','artists','appointments'].includes(section))throw new Error('Forbidden');return user}
async function audit(actorId:string,action:string,entity:string,entityId:string|undefined,after?:Input){await db.auditLog.create({data:{actorId,action,entity,entityId,after:after as Prisma.InputJsonValue}})}
async function mutate(req:NextRequest,context:{params:Promise<{section:string}>},method:'POST'|'PATCH'|'DELETE'){
  const {section}=await context.params;
  try{const user=await authorize(req,section);const body=await req.json();const id=str(body.id);const data=(body.data||{}) as Input;if(method!=='POST'&&!id)throw new Error('Missing ID');if(method==='POST'&&user.role==='ARTIST'&&!['availability','blockedTimes','gallery'].includes(section))throw new Error('Forbidden');let result:{id?:string}|null=null;
    if(method==='DELETE'){
      if(user.role==='ARTIST')throw new Error('Forbidden');
      switch(section){case 'services':await db.service.update({where:{id},data:{active:false,bookingEnabled:false}});break;case 'options':await db.serviceOption.delete({where:{id}});break;case 'categories':await db.category.update({where:{id},data:{active:false}});break;case 'artists':await db.artist.update({where:{id},data:{active:false,bookingEnabled:false}});break;case 'team':if(id===user.id)throw new Error('Cannot delete your own account');await db.user.delete({where:{id}});break;case 'gallery':await db.galleryItem.delete({where:{id}});break;case 'social':await db.socialPost.delete({where:{id}});break;case 'testimonials':await db.testimonial.delete({where:{id}});break;case 'content':await db.contentBlock.delete({where:{id}});break;case 'policies':await db.policy.delete({where:{id}});break;case 'faqs':await db.fAQ.delete({where:{id}});break;case 'notifications':await db.notificationTemplate.delete({where:{id}});break;case 'availability':await db.availability.delete({where:{id}});break;case 'blockedTimes':await db.blockedTime.delete({where:{id}});break;default:throw new Error('Delete unavailable')}
      await audit(user.id,'delete',section,id);return NextResponse.json({ok:true});
    }
    const create=method==='POST';
    switch(section){
      case 'team':{const email=str(data.email).toLowerCase(),role=str(data.role) as 'ADMIN'|'ARTIST',artistId=optional(data.artistId),password=str(data.password);if(!email.includes('@')||!['ADMIN','ARTIST'].includes(role)||role==='ARTIST'&&!artistId)throw new Error('Enter a valid email, role, and artist profile');if(create&&!password)throw new Error('A password is required');if(password&&password.length<12)throw new Error('Password must be at least 12 characters');if(artistId){const linkedArtist=await db.artist.findUnique({where:{id:artistId},select:{userId:true}});if(linkedArtist?.userId&&(create||linkedArtist.userId!==id))throw new Error('Artist profile is already assigned to another team member')}const input={email,role,verifiedAt:new Date(),...(password?{passwordHash:await hash(password,12)}:{})};result=create?await db.user.create({data:{...input,artists:artistId?{connect:{id:artistId}}:undefined}}):await db.user.update({where:{id},data:{...input,artists:{set:artistId?[{id:artistId}]:[]}}});break}
      case 'social':{const input={platform:str(data.platform||'Instagram'),mediaUrl:str(data.mediaUrl),destinationUrl:str(data.destinationUrl),altText:str(data.altText),caption:optional(data.caption),featured:bool(data.featured),published:bool(data.published),displayOrder:num(data.displayOrder)||0};if(!input.mediaUrl||!input.destinationUrl||!input.altText)throw new Error('Media, post URL, and alt text required');result=create?await db.socialPost.create({data:input}):await db.socialPost.update({where:{id},data:input});break}
      case 'options':{const input={serviceId:str(data.serviceId),name:str(data.name),description:optional(data.description),priceDelta:Math.round(Number(data.priceDelta||0)*100),durationDelta:num(data.durationDelta)||0,required:bool(data.required),active:bool(data.active),displayOrder:num(data.displayOrder)||0};if(!input.serviceId||!input.name)throw new Error('Service and name required');result=create?await db.serviceOption.create({data:input}):await db.serviceOption.update({where:{id},data:input});break}
      case 'services':{
        if(user.role==='ARTIST'){const existing=await db.service.findUnique({where:{id},include:{artists:true}});if(!existing?.artists.some(a=>a.artistId===user.artist?.id)||arr(data.artistIds).some(artistId=>artistId!==user.artist?.id))throw new Error('Forbidden')}
        const artistIds=arr(data.artistIds);const depositType=str(data.depositType||'NONE') as 'NONE'|'FLAT'|'PERCENT';const input={name:str(data.name),slug:str(data.slug),categoryId:str(data.categoryId),shortDescription:optional(data.shortDescription),description:optional(data.description),priceType:str(data.priceType||'VARIES') as 'VARIES',priceMin:num(data.priceMin)==null?null:Math.round(Number(data.priceMin)*100),priceMax:num(data.priceMax)==null?null:Math.round(Number(data.priceMax)*100),durationMinutes:num(data.durationMinutes),bufferBefore:num(data.bufferBefore)||0,bufferAfter:num(data.bufferAfter)||0,depositType,depositValue:num(data.depositValue)==null?null:depositType==='FLAT'?Math.round(Number(data.depositValue)*100):Number(data.depositValue),preparation:optional(data.preparation),aftercare:optional(data.aftercare),imageUrl:optional(data.imageUrl),active:bool(data.active),featured:bool(data.featured),bookingEnabled:bool(data.bookingEnabled),displayOrder:num(data.displayOrder)||0};
        if(!input.name||!input.slug||!input.categoryId)throw new Error('Name, slug and category are required');if(input.bookingEnabled&&(!input.durationMinutes||input.durationMinutes<15||!artistIds.length))throw new Error('Set a duration and artist before enabling booking');if(input.bufferBefore<0||input.bufferAfter<0||input.durationMinutes!=null&&input.durationMinutes<0)throw new Error('Invalid duration or buffer');if(input.depositType!=='NONE'&&(input.priceMin==null||input.depositValue==null||input.depositValue<0||input.depositType==='PERCENT'&&input.depositValue>100))throw new Error('Deposit needs a valid price and amount');
        result=create?await db.service.create({data:{...input,artists:{create:artistIds.map(artistId=>({artistId}))}}}):await db.service.update({where:{id},data:{...input,artists:{deleteMany:{},create:artistIds.map(artistId=>({artistId}))}}});break}
      case 'categories':{const input={name:str(data.name),slug:str(data.slug),description:optional(data.description),displayOrder:num(data.displayOrder)||0,active:bool(data.active)};if(!input.name||!input.slug)throw new Error('Name and slug required');result=create?await db.category.create({data:input}):await db.category.update({where:{id},data:input});break}
      case 'artists':{if(user.role==='ARTIST'&&id!==user.artist?.id)throw new Error('Forbidden');const input={name:str(data.name),displayName:str(data.displayName),slug:str(data.slug),roleLabels:arr(data.roleLabels),specialties:arr(data.specialties),bio:optional(data.bio),photoUrl:optional(data.photoUrl),coverUrl:optional(data.coverUrl),instagramUrl:optional(data.instagramUrl),tiktokUrl:optional(data.tiktokUrl),active:bool(data.active),bookingEnabled:bool(data.bookingEnabled),displayOrder:num(data.displayOrder)||0};if(!input.name||!input.slug)throw new Error('Name and slug required');result=create?await db.artist.create({data:input}):await db.artist.update({where:{id},data:input});break}
      case 'gallery':{const artistId=optional(data.artistId);if(user.role==='ARTIST'){const existing=create?null:await db.galleryItem.findUnique({where:{id}});if(artistId!==user.artist?.id||existing&&existing.artistId!==user.artist?.id)throw new Error('Forbidden')}const input={imageUrl:optional(data.imageUrl),beforeUrl:optional(data.beforeUrl),afterUrl:optional(data.afterUrl),caption:optional(data.caption),altText:str(data.altText),categoryId:optional(data.categoryId),artistId,serviceId:optional(data.serviceId),featured:bool(data.featured),published:bool(data.published),displayOrder:num(data.displayOrder)||0};if(!input.altText||!input.imageUrl&&!input.beforeUrl)throw new Error('Image and alt text required');result=create?await db.galleryItem.create({data:input}):await db.galleryItem.update({where:{id},data:input});break}
      case 'testimonials':{const input={displayName:str(data.displayName),rating:num(data.rating)||5,text:str(data.text),status:str(data.status||'DRAFT') as 'DRAFT',featured:bool(data.featured)};if(!input.displayName||!input.text||input.rating<1||input.rating>5)throw new Error('Valid name, rating and testimonial required');result=create?await db.testimonial.create({data:input}):await db.testimonial.update({where:{id},data:input});break}
      case 'content':{const input={key:str(data.key),title:optional(data.title),body:optional(data.body),imageUrl:optional(data.imageUrl),ctaLabel:optional(data.ctaLabel),ctaUrl:optional(data.ctaUrl),status:str(data.status||'DRAFT') as 'DRAFT'};if(!input.key)throw new Error('Content key required');result=create?await db.contentBlock.create({data:input}):await db.contentBlock.update({where:{id},data:input});break}
      case 'policies':{const input={title:str(data.title),slug:str(data.slug),body:str(data.body),status:str(data.status||'DRAFT') as PublishStatus,displayOrder:num(data.displayOrder)||0};if(!input.title||!input.slug)throw new Error('Title and slug required');result=await db.$transaction(async tx=>{const policy=create?await tx.policy.create({data:input}):await tx.policy.update({where:{id},data:input});if(input.status==='PUBLISHED'&&input.body){const latest=await tx.policyVersion.findFirst({where:{policyId:policy.id},orderBy:{version:'desc'}});if(latest?.body!==input.body)await tx.policyVersion.create({data:{policyId:policy.id,version:(latest?.version||0)+1,body:input.body}})}return policy});break}
      case 'faqs':{const input={category:str(data.category),question:str(data.question),answer:str(data.answer),status:str(data.status||'DRAFT') as 'DRAFT',displayOrder:num(data.displayOrder)||0};if(!input.category||!input.question||!input.answer)throw new Error('Complete all FAQ fields');result=create?await db.fAQ.create({data:input}):await db.fAQ.update({where:{id},data:input});break}
      case 'notifications':{const input={event:str(data.event),channel:str(data.channel||'email'),subject:optional(data.subject),body:str(data.body),active:bool(data.active)};result=create?await db.notificationTemplate.create({data:input}):await db.notificationTemplate.update({where:{id},data:input});break}
      case 'settings':{const key=str(data.key);if(!key)throw new Error('Setting key required');const value=JSON.parse(str(data.value));await db.siteSetting.upsert({where:{key},create:{key,value},update:{value}});result={id:key};break}
      case 'clients':{if(create)throw new Error('Clients are created through bookings');result=await db.client.update({where:{id},data:{name:str(data.name),email:str(data.email),phone:optional(data.phone),notes:optional(data.notes),tags:arr(data.tags)}});break}
      case 'inquiries':{if(create)throw new Error('Unsupported');result=await db.inquiry.update({where:{id},data:{status:str(data.status)}});break}
      case 'appointments':{if(create)throw new Error('Unsupported');const existing=await db.appointment.findUnique({where:{id}});if(user.role==='ARTIST'&&existing?.artistId!==user.artist?.id)throw new Error('Forbidden');const update={status:str(data.status) as BookingStatus,paymentStatus:str(data.paymentStatus) as PaymentStatus,internalNotes:optional(data.internalNotes),history:{create:{action:'admin_updated',actorId:user.id}}};result=await db.$transaction(async tx=>{if(existing?.status==='CANCELLED'&&['PENDING','CONFIRMED'].includes(update.status)){const overlapping=await tx.appointment.count({where:{artistId:existing.artistId,id:{not:id},status:{in:['PENDING','CONFIRMED']},reservedStartAt:{lt:existing.reservedEndAt},reservedEndAt:{gt:existing.reservedStartAt}}});const blocked=await tx.blockedTime.count({where:{artistId:existing.artistId,startAt:{lt:existing.reservedEndAt},endAt:{gt:existing.reservedStartAt}}});if(overlapping||blocked)throw new Error('This appointment conflicts with an existing booking or blocked time');await acquireSlotLocks(tx,existing.artistId,existing.reservedStartAt,existing.reservedEndAt,id)}const appointment=await tx.appointment.update({where:{id},data:update});if(update.status==='CANCELLED')await tx.bookingSlotLock.deleteMany({where:{appointmentId:id}});return appointment});break}
      case 'availability':{const artistId=str(data.artistId);if(user.role==='ARTIST'){const existing=create?null:await db.availability.findUnique({where:{id}});if(artistId!==user.artist?.id||existing&&existing.artistId!==user.artist?.id)throw new Error('Forbidden')}const input={artistId,weekday:num(data.weekday)||0,date:optional(data.date),startMinute:num(data.startMinute)||0,endMinute:num(data.endMinute)||0};if(input.weekday<0||input.weekday>6||input.startMinute<0||input.endMinute>1440||input.endMinute<=input.startMinute||input.date&&!/^\d{4}-\d{2}-\d{2}$/.test(input.date))throw new Error('Invalid schedule');result=create?await db.availability.create({data:input}):await db.availability.update({where:{id},data:input});break}
      case 'blockedTimes':{const artistId=str(data.artistId);if(user.role==='ARTIST'){const existing=create?null:await db.blockedTime.findUnique({where:{id}});if(artistId!==user.artist?.id||existing&&existing.artistId!==user.artist?.id)throw new Error('Forbidden')}const input={artistId,startAt:new Date(str(data.startAt)),endAt:new Date(str(data.endAt)),reason:optional(data.reason)};if(!(input.startAt<input.endAt))throw new Error('Invalid blocked time');result=create?await db.blockedTime.create({data:input}):await db.blockedTime.update({where:{id},data:input});break}
    }
    await audit(user.id,create?'create':'update',section,result?.id||id,data);return NextResponse.json({ok:true,id:result?.id});
  }catch(e){return errorResponse(e,e instanceof SyntaxError?400:400)}
}
export async function POST(req:NextRequest,ctx:{params:Promise<{section:string}>}){return mutate(req,ctx,'POST')}
export async function PATCH(req:NextRequest,ctx:{params:Promise<{section:string}>}){return mutate(req,ctx,'PATCH')}
export async function DELETE(req:NextRequest,ctx:{params:Promise<{section:string}>}){return mutate(req,ctx,'DELETE')}
