import Link from 'next/link';
import { DateTime } from 'luxon';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { zone } from '@/lib/booking';
import { money } from '@/lib/site';
export default async function Dashboard(){
 const user=await requireUser(['OWNER','ADMIN','ARTIST']);const own=user.role==='ARTIST'?user.artist?.id:undefined;
 const filter=own?{artistId:own}:{};const now=DateTime.now().setZone(zone);const start=now.startOf('day').toJSDate(),weekStart=now.startOf('week').toJSDate(),end=now.plus({days:1}).startOf('day').toJSDate(),weekEnd=now.endOf('week').plus({milliseconds:1}).toJSDate();
 const [today,week,pending,deposits,next,recent,clients,inquiries,payments]=await Promise.all([
  db.appointment.findMany({where:{...filter,startAt:{gte:start,lt:end},status:{in:['PENDING','CONFIRMED']}},include:{client:true,artist:true,service:true},orderBy:{startAt:'asc'}}),
  db.appointment.count({where:{...filter,startAt:{gte:weekStart,lt:weekEnd},status:{in:['PENDING','CONFIRMED']}}}),
  db.appointment.count({where:{...filter,status:'PENDING'}}),
  db.appointment.count({where:{...filter,paymentStatus:'PENDING',depositDue:{gt:0},status:{not:'CANCELLED'}}}),
  db.appointment.findFirst({where:{...filter,startAt:{gte:now.toJSDate()},status:{in:['PENDING','CONFIRMED']}},include:{client:true,artist:true,service:true},orderBy:{startAt:'asc'}}),
  db.appointment.findMany({where:filter,include:{client:true,service:true},orderBy:{createdAt:'desc'},take:5}),
  user.role==='ARTIST'?Promise.resolve(null):db.client.count(),
  user.role==='ARTIST'?Promise.resolve(null):db.inquiry.count({where:{status:'new'}}),
  user.role==='ARTIST'?Promise.resolve(null):db.payment.aggregate({where:{status:'paid',createdAt:{gte:now.startOf('month').toJSDate()}},_sum:{amount:true}})
 ]);
 const date=(value:Date)=>new Intl.DateTimeFormat('en-US',{timeZone:zone,weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(value);
 return <><div className="admin-toolbar"><div><p className="eyebrow">{now.toFormat('EEEE, MMMM d')}</p><h1 className="admin-title">Good {now.hour<12?'morning':now.hour<17?'afternoon':'evening'}.</h1><p className="muted">Here is what is happening at the studio.</p></div><Link className="button button-dark" href="/admin/calendar">View schedule</Link></div><div className="stat-grid"><div className="stat"><span>Appointments today</span><strong>{today.length}</strong></div><div className="stat"><span>This week</span><strong>{week}</strong></div><div className="stat"><span>Pending requests</span><strong>{pending}</strong></div><div className="stat"><span>Deposits awaiting payment</span><strong>{deposits}</strong></div>{clients!==null&&<div className="stat"><span>Clients</span><strong>{clients}</strong></div>}{inquiries!==null&&<div className="stat"><span>New inquiries</span><strong>{inquiries}</strong></div>}{payments!==null&&<div className="stat"><span>Paid online this month</span><strong>{money(payments._sum.amount||0)}</strong></div>}</div><div className="admin-dashboard-grid"><section className="admin-panel"><p className="eyebrow">Today</p><h2>Appointment schedule</h2>{today.length?today.map(a=><Link className="list-row" href="/admin/appointments" key={a.id}><span><strong>{date(a.startAt)}</strong><br/>{a.client.name} · {a.service.name}<br/><small>{a.artist.displayName}</small></span><span className="badge">{a.status.toLowerCase()}</span></Link>):<div className="empty-state">No appointments today. Your schedule is clear.</div>}</section><section className="admin-panel"><p className="eyebrow">Coming up</p><h2>Next appointment</h2>{next?<><p><strong>{next.client.name}</strong> · {next.service.name}</p><p>{date(next.startAt)} with {next.artist.displayName}</p><span className="badge">{next.status.toLowerCase()}</span></>:<p className="muted">Nothing booked yet.</p>}<h3>Quick actions</h3><div className="admin-quick-actions"><Link href="/admin/calendar?view=blockedTimes">Add blocked time</Link><Link href="/admin/services">Add service</Link><Link href="/admin/gallery">Upload gallery photo</Link><Link href="/admin/clients">View clients</Link><Link href="/admin/calendar">Today’s schedule</Link><Link href="/book">Book appointment</Link></div></section></div><section className="admin-panel"><div className="admin-toolbar"><h2>Recent bookings</h2><Link className="text-link" href="/admin/appointments">All appointments</Link></div>{recent.length?<div className="table-wrap"><table><thead><tr><th>Client</th><th>Service</th><th>When</th><th>Status</th></tr></thead><tbody>{recent.map(a=><tr key={a.id}><td>{a.client.name}</td><td>{a.service.name}</td><td>{date(a.startAt)}</td><td><span className="badge">{a.status.toLowerCase()}</span></td></tr>)}</tbody></table></div>:<div className="empty-state">Bookings will appear here as clients schedule.</div>}</section></>
}
