'use client';
import { DateTime } from 'luxon';
import { useMemo,useState } from 'react';
type Appointment={id:string;reference:string;startAt:string;endAt:string;status:string;client:{name:string};artist:{displayName:string;id:string};service:{name:string}};
type Block={id:string;artistId:string;startAt:string;endAt:string;reason:string|null};
const key=(date:Date,timeZone:string)=>DateTime.fromJSDate(date).setZone(timeZone).toFormat('yyyy-MM-dd');
export default function CalendarView({records,artists,blockedTimes,timeZone}:{records:Appointment[];artists:{id:string;displayName:string}[];blockedTimes:Block[];timeZone:string}){
 const [view,setView]=useState<'day'|'week'|'month'>('week'),[date,setDate]=useState(key(new Date(),timeZone)),[artist,setArtist]=useState('');
 const visible=useMemo(()=>{const selected=DateTime.fromISO(date,{zone:timeZone}).startOf('day');if(!selected.isValid)return [];const start=view==='day'?selected:view==='week'?selected.minus({days:selected.weekday%7}):selected.startOf('month');const end=view==='day'?start.plus({days:1}):view==='week'?start.plus({days:7}):start.plus({months:1});const appointments=records.filter(r=>{const stamp=Date.parse(r.startAt);return stamp>=start.toMillis()&&stamp<end.toMillis()&&(!artist||r.artist.id===artist)}).map(r=>({...r,kind:'appointment' as const}));const blocks=blockedTimes.filter(r=>{const stamp=Date.parse(r.startAt);return stamp<end.toMillis()&&Date.parse(r.endAt)>start.toMillis()&&(!artist||r.artistId===artist)}).map(r=>({...r,kind:'block' as const}));return [...appointments,...blocks].sort((a,b)=>Date.parse(a.startAt)-Date.parse(b.startAt))},[records,blockedTimes,date,view,artist,timeZone]);
 const grouped=Object.groupBy(visible,r=>key(new Date(r.startAt),timeZone));const time=(iso:string)=>DateTime.fromISO(iso).setZone(timeZone).toFormat('h:mm a');
 return <><div className="admin-toolbar"><div className="filter-row">{(['day','week','month'] as const).map(v=><button className={`filter-pill ${view===v?'active':''}`} key={v} onClick={()=>setView(v)}>{v}</button>)}</div><div className="actions" style={{margin:0}}><input type="date" className="search-input" aria-label="Calendar date" value={date} onChange={e=>setDate(e.target.value)}/><select className="search-input" aria-label="Filter artist" value={artist} onChange={e=>setArtist(e.target.value)}><option value="">All artists</option>{artists.map(a=><option value={a.id} key={a.id}>{a.displayName}</option>)}</select></div></div>{visible.length?<div className="stack">{Object.entries(grouped).map(([day,items])=><section className="service-card" key={day}><p className="eyebrow">{DateTime.fromISO(day,{zone:timeZone}).toFormat('EEEE, LLLL d')}</p>{items?.map(item=><div className="list-row" key={item.id}><div><strong>{time(item.startAt)} to {time(item.endAt)} · {item.kind==='appointment'?item.service.name:item.reason||'Blocked time'}</strong><p>{item.kind==='appointment'?`${item.client.name} with ${item.artist.displayName}`:artists.find(a=>a.id===item.artistId)?.displayName||'Studio'}</p></div><span className="badge">{item.kind==='appointment'?item.status.toLowerCase().replaceAll('_',' '):'Unavailable'}</span></div>)}</section>)}</div>:<div className="empty-state">No appointments or blocked time in this {view}.</div>}</>
}
