'use client';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import Link from 'next/link';
import CalendarView from './calendar-view';
type Row=Record<string,unknown>;
type Field={key:string;label:string;type?:'text'|'textarea'|'number'|'checkbox'|'select'|'date'|'money';options?:string[];required?:boolean};
const fields:Record<string,Field[]>={
  services:[{key:'name',label:'Service name',required:true},{key:'slug',label:'URL slug',required:true},{key:'categoryId',label:'Category',type:'select',required:true},{key:'artistIds',label:'Artist IDs (comma separated)'},{key:'shortDescription',label:'Short description',type:'textarea'},{key:'description',label:'Full description',type:'textarea'},{key:'priceType',label:'Price type',type:'select',options:['FIXED','STARTING','RANGE','VARIES','CONSULTATION']},{key:'priceMin',label:'Minimum / fixed price ($)',type:'money'},{key:'priceMax',label:'Maximum price ($)',type:'money'},{key:'durationMinutes',label:'Duration (minutes)',type:'number'},{key:'bufferBefore',label:'Buffer before (minutes)',type:'number'},{key:'bufferAfter',label:'Buffer after (minutes)',type:'number'},{key:'depositType',label:'Deposit type',type:'select',options:['NONE','FLAT','PERCENT']},{key:'depositValue',label:'Deposit ($ or %)',type:'number'},{key:'preparation',label:'Preparation',type:'textarea'},{key:'aftercare',label:'Aftercare',type:'textarea'},{key:'imageUrl',label:'Image URL'},{key:'active',label:'Active',type:'checkbox'},{key:'featured',label:'Featured',type:'checkbox'},{key:'bookingEnabled',label:'Booking enabled',type:'checkbox'},{key:'displayOrder',label:'Display order',type:'number'}],
  options:[{key:'serviceId',label:'Service',type:'select',required:true},{key:'name',label:'Option name',required:true},{key:'description',label:'Description',type:'textarea'},{key:'priceDelta',label:'Additional price ($)',type:'money'},{key:'durationDelta',label:'Additional minutes',type:'number'},{key:'required',label:'Required',type:'checkbox'},{key:'active',label:'Active',type:'checkbox'},{key:'displayOrder',label:'Display order',type:'number'}],
  categories:[{key:'name',label:'Name',required:true},{key:'slug',label:'Slug',required:true},{key:'description',label:'Description',type:'textarea'},{key:'displayOrder',label:'Display order',type:'number'},{key:'active',label:'Active',type:'checkbox'}],
  artists:[{key:'displayName',label:'Display name',required:true},{key:'name',label:'Name',required:true},{key:'slug',label:'Slug',required:true},{key:'roleLabels',label:'Roles (comma separated)'},{key:'specialties',label:'Specialties (comma separated)'},{key:'bio',label:'Bio',type:'textarea'},{key:'photoUrl',label:'Photo URL'},{key:'coverUrl',label:'Cover URL'},{key:'instagramUrl',label:'Instagram URL'},{key:'tiktokUrl',label:'TikTok URL'},{key:'active',label:'Active',type:'checkbox'},{key:'bookingEnabled',label:'Booking enabled',type:'checkbox'},{key:'displayOrder',label:'Display order',type:'number'}],
  team:[{key:'email',label:'Email',required:true},{key:'role',label:'Role',type:'select',options:['ADMIN','ARTIST']},{key:'artistId',label:'Artist profile',type:'select'},{key:'password',label:'Password (required on creation; leave blank to retain)' }],
  gallery:[{key:'imageUrl',label:'Image URL'},{key:'beforeUrl',label:'Before image URL'},{key:'afterUrl',label:'After image URL'},{key:'caption',label:'Caption'},{key:'altText',label:'Alt text',required:true},{key:'categoryId',label:'Category',type:'select'},{key:'artistId',label:'Artist',type:'select'},{key:'serviceId',label:'Service',type:'select'},{key:'featured',label:'Featured',type:'checkbox'},{key:'published',label:'Published',type:'checkbox'},{key:'displayOrder',label:'Display order',type:'number'}],
  social:[{key:'platform',label:'Platform',type:'select',options:['Instagram','TikTok','Other']},{key:'mediaUrl',label:'Media URL',required:true},{key:'destinationUrl',label:'Post URL',required:true},{key:'altText',label:'Alt text',required:true},{key:'caption',label:'Caption'},{key:'featured',label:'Featured',type:'checkbox'},{key:'published',label:'Published',type:'checkbox'},{key:'displayOrder',label:'Display order',type:'number'}],
  testimonials:[{key:'displayName',label:'Client display name',required:true},{key:'rating',label:'Rating 1–5',type:'number'},{key:'text',label:'Testimonial',type:'textarea',required:true},{key:'status',label:'Status',type:'select',options:['DRAFT','PUBLISHED']},{key:'featured',label:'Featured',type:'checkbox'}],
  content:[{key:'key',label:'Content key',required:true},{key:'title',label:'Title'},{key:'body',label:'Body',type:'textarea'},{key:'imageUrl',label:'Image URL'},{key:'ctaLabel',label:'CTA label'},{key:'ctaUrl',label:'CTA URL'},{key:'status',label:'Status',type:'select',options:['DRAFT','PUBLISHED']}],
  policies:[{key:'title',label:'Title',required:true},{key:'slug',label:'Slug',required:true},{key:'body',label:'Policy text',type:'textarea'},{key:'status',label:'Status',type:'select',options:['DRAFT','PUBLISHED']},{key:'displayOrder',label:'Display order',type:'number'}],
  faqs:[{key:'category',label:'Category',required:true},{key:'question',label:'Question',required:true},{key:'answer',label:'Answer',type:'textarea',required:true},{key:'status',label:'Status',type:'select',options:['DRAFT','PUBLISHED']},{key:'displayOrder',label:'Display order',type:'number'}],
  notifications:[{key:'event',label:'Event',required:true},{key:'channel',label:'Channel',type:'select',options:['email','sms']},{key:'subject',label:'Subject'},{key:'body',label:'HTML body',type:'textarea'},{key:'active',label:'Active',type:'checkbox'}],
  settings:[{key:'key',label:'Setting key',required:true},{key:'value',label:'JSON value',type:'textarea',required:true}],
  clients:[{key:'name',label:'Name'},{key:'email',label:'Email'},{key:'phone',label:'Phone'},{key:'notes',label:'Internal notes',type:'textarea'},{key:'tags',label:'Tags (comma separated)'}],
  inquiries:[{key:'status',label:'Status',type:'select',options:['new','open','resolved']}],
  appointments:[{key:'status',label:'Status',type:'select',options:['PENDING','CONFIRMED','COMPLETED','CANCELLED','NO_SHOW']},{key:'paymentStatus',label:'Payment status',type:'select',options:['NOT_REQUIRED','PENDING','DEPOSIT_PAID','PAID','PARTIALLY_PAID','REFUNDED','PARTIALLY_REFUNDED']},{key:'internalNotes',label:'Internal notes',type:'textarea'}],
  availability:[{key:'artistId',label:'Artist',type:'select',required:true},{key:'weekday',label:'Weekday (0 Sun–6 Sat)',type:'number',required:true},{key:'date',label:'Special date (YYYY-MM-DD), optional'},{key:'startMinute',label:'Start minutes after midnight',type:'number',required:true},{key:'endMinute',label:'End minutes after midnight',type:'number',required:true}],
  blockedTimes:[{key:'artistId',label:'Artist',type:'select',required:true},{key:'startAt',label:'Start (ISO date/time)',required:true},{key:'endAt',label:'End (ISO date/time)',required:true},{key:'reason',label:'Reason'}]
};
function label(row:Row,section:string){if(section==='team')return String(row.email);if(section==='services'||section==='options'||section==='categories'||section==='artists')return String(row.name||row.displayName);if(section==='appointments')return `${row.reference} · ${(row.client as Row)?.name||''}`;if(section==='calendar')return `${(row.service as Row)?.name||''} · ${(row.client as Row)?.name||''}`;if(section==='clients'||section==='inquiries')return String(row.name);if(section==='gallery'||section==='social')return String(row.caption||row.altText);if(section==='testimonials')return String(row.displayName);if(section==='policies')return String(row.title);if(section==='faqs')return String(row.question);if(section==='content'||section==='settings')return String(row.key);if(section==='notifications')return String(row.event);if(section==='media')return String(row.altText);return String(row.name||'Event')}
function seedForm(row:Row,section:string){const value={...row};if(section==='team')value.artistId=((row.artists as Row[]||[])[0])?.id||'';if(section==='services')value.artistIds=(row.artists as Row[]||[]).map(a=>a.artistId).join(', ');for(const key of ['roleLabels','specialties','tags'])if(Array.isArray(value[key]))value[key]=(value[key] as string[]).join(', ');if(section==='settings')value.value=JSON.stringify(value.value,null,2);for(const key of ['priceMin','priceMax','priceDelta'])if(typeof value[key]==='number')value[key]=Number(value[key])/100;if(value.depositType==='FLAT'&&typeof value.depositValue==='number')value.depositValue=Number(value.depositValue)/100;return value}
export default function Manager({section,records,total,page,query,extra,role,timeZone}:{section:string;records:Row[];total:number;page:number;query:string;extra:Record<string,unknown>;role:string;timeZone:string}){const router=useRouter();const [editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState<Row>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[subsection,setSubsection]=useState<'appointments'|'availability'|'blockedTimes'>('appointments');const activeSection=section==='calendar'?subsection:section;const defs=fields[activeSection]||[];const canCreate=!['appointments','clients','inquiries','analytics','media'].includes(activeSection)&&(role!=='ARTIST'||['availability','blockedTimes','gallery'].includes(activeSection));
  function edit(row:Row){setEditing(row);setForm(seedForm(row,activeSection));setMessage('')}
  function create(){setEditing({});setForm({active:true,bookingEnabled:false,featured:false,published:false,status:'DRAFT',priceType:'VARIES',depositType:'NONE',displayOrder:0,channel:'email'});setMessage('')}
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const response=await fetch(`/api/admin/${activeSection}`,{method:editing?.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editing?.id,data:form})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Save failed');setEditing(null);setMessage('Saved.');router.refresh()}catch(err){setMessage(err instanceof Error?err.message:'Save failed')}finally{setBusy(false)}}
  async function remove(row:Row){const archive=['services','categories','artists'].includes(activeSection);if(!confirm(`${archive?'Archive':'Delete'} ${label(row,activeSection)}?`))return;const response=await fetch(`/api/admin/${activeSection}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});const data=await response.json();setMessage(data.error||(archive?'Archived.':'Deleted.'));if(response.ok)router.refresh()}
  async function duplicate(row:Row){const response=await fetch('/api/admin/services/duplicate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});const data=await response.json();setMessage(data.error||'Draft copy created.');if(response.ok)router.refresh()}
  const shown=section==='calendar'?(subsection==='appointments'?records:subsection==='availability'?(extra.availability as Row[]||[]):(extra.blockedTimes as Row[]||[])):records;
  return <><div className="admin-toolbar">{section==='calendar'?<div className="filter-row">{(['appointments','availability','blockedTimes'] as const).map(s=><button className={`filter-pill ${subsection===s?'active':''}`} key={s} onClick={()=>setSubsection(s)}>{s==='blockedTimes'?'Blocked time':s}</button>)}</div>:<form action={`/admin/${section}`} className="actions" style={{margin:0}}><input className="search-input" style={{width:260}} name="q" defaultValue={query} placeholder="Search" aria-label="Search records"/><button className="button button-outline">Search</button></form>}{canCreate&&<button className="button button-dark" onClick={create}>Add new ↗</button>}</div>{message&&<p className="notice" role="status">{message}</p>}
  {section==='analytics'&&<p className="notice">Last 30 days. Paid transactions: {Number(((extra.payments as Row)?._sum as Row)?.amount||0)/100} USD.</p>}
  {section==='media'&&<MediaUpload onDone={()=>router.refresh()}/>}
  {section==='calendar'&&subsection==='appointments'?<CalendarView records={shown as unknown as Parameters<typeof CalendarView>[0]['records']} artists={extra.artists as Parameters<typeof CalendarView>[0]['artists']||[]} timeZone={timeZone}/>:shown.length?<div className="table-wrap"><table><thead><tr><th>Record</th><th>Details</th><th>Updated / status</th><th>Actions</th></tr></thead><tbody>{shown.map((row,i)=><tr key={String(row.id||i)}><td><strong>{activeSection==='clients'?<Link href={`/admin/clients/${row.id}`}>{label(row,activeSection)} ↗</Link>:label(row,activeSection)}</strong></td><td>{activeSection==='services'?String((row.category as Row)?.name||''):activeSection==='appointments'||activeSection==='calendar'?String((row.artist as Row)?.displayName||''):activeSection==='availability'?`Day ${row.weekday} · ${row.startMinute}–${row.endMinute}`:activeSection==='analytics'?String((row._count as Row)?.name||''):String(row.email||row.category||row.slug||'')}</td><td>{String(row.status||row.startAt||row.updatedAt||row.createdAt||'')}</td><td>{defs.length>0&&<button className="text-link" onClick={()=>edit(row)}>Edit</button>}{activeSection==='services'&&role!=='ARTIST'&&<button className="text-link" style={{marginLeft:15}} onClick={()=>duplicate(row)}>Duplicate</button>}{!['appointments','clients','inquiries'].includes(activeSection)&&defs.length>0&&role!=='ARTIST'&&<button className="text-link" style={{marginLeft:15}} onClick={()=>remove(row)}>{['services','categories','artists'].includes(activeSection)?'Archive':'Delete'}</button>}</td></tr>)}</tbody></table></div>:<div className="empty-state">No records here yet.</div>}
  {section!=='calendar'&&total>20&&<div className="actions"><button className="button button-outline" disabled={page<=1} onClick={()=>router.push(`/admin/${section}?q=${encodeURIComponent(query)}&page=${page-1}`)}>Previous</button><span>Page {page} of {Math.ceil(total/20)}</span><button className="button button-outline" disabled={page*20>=total} onClick={()=>router.push(`/admin/${section}?q=${encodeURIComponent(query)}&page=${page+1}`)}>Next</button></div>}
  {editing&&<div style={{position:'fixed',inset:0,zIndex:100,background:'rgba(0,0,0,.58)',overflowY:'auto',padding:'30px 16px'}} role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><div className="admin-form" role="dialog" aria-modal="true" aria-label={`Edit ${activeSection}`} style={{margin:'auto'}}><div className="admin-toolbar"><h2 style={{fontSize:'2rem'}}>{editing.id?'Edit':'Add'} {activeSection}</h2><button className="button button-outline" onClick={()=>setEditing(null)}>Close</button></div><form onSubmit={save} className="form-grid">{defs.map(field=>{const value=form[field.key];let options=field.options;if(field.key==='categoryId')options=(extra.categories as Row[]||[]).map(r=>`${r.id}|${r.name}`);if(field.key==='artistId')options=(extra.artists as Row[]||[]).map(r=>`${r.id}|${r.displayName}`);if(field.key==='serviceId')options=(extra.services as Row[]||[]).map(r=>`${r.id}|${r.name}`);return <div className={`field ${field.type==='textarea'?'full':''}`} key={field.key}><label htmlFor={`field-${field.key}`}>{field.label}</label>{field.type==='checkbox'?<input id={`field-${field.key}`} type="checkbox" checked={Boolean(value)} onChange={e=>setForm({...form,[field.key]:e.target.checked})}/>:field.type==='textarea'?<textarea id={`field-${field.key}`} required={field.required} value={String(value??'')} onChange={e=>setForm({...form,[field.key]:e.target.value})}/>:field.type==='select'?<select id={`field-${field.key}`} required={field.required} value={String(value??'')} onChange={e=>setForm({...form,[field.key]:e.target.value})}><option value="">Choose…</option>{options?.map(option=>{const [val,label]=option.includes('|')?option.split('|'):[option,option];return <option value={val} key={val}>{label}</option>})}</select>:<input id={`field-${field.key}`} required={field.required} type={field.type==='number'||field.type==='money'?'number':'text'} step={field.type==='money'?'0.01':field.type==='number'?'1':undefined} value={String(value??'')} onChange={e=>setForm({...form,[field.key]:e.target.value})}/>}</div>})}<div className="field full"><button className="button button-dark" disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></form>{message&&<p role="alert" className="notice">{message}</p>}</div></div>}</>}
function MediaUpload({onDone}:{onDone:()=>void}){const [message,setMessage]=useState('');async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const body=new FormData(form);const r=await fetch('/api/admin/media',{method:'POST',body});const data=await r.json();setMessage(r.ok?`Uploaded: ${data.url}`:data.error);if(r.ok){form.reset();onDone()}}return <form className="admin-form form-grid" onSubmit={upload}><div className="field"><label htmlFor="media-file">Image</label><input id="media-file" name="file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" required/></div><div className="field"><label htmlFor="media-alt">Alt text</label><input id="media-alt" name="altText" required/></div><button className="button button-dark">Upload image</button>{message&&<p role="status">{message}</p>}</form>}
