'use client';
import { useEffect,useState } from 'react';
import Image from 'next/image';
type Media={id:string;url:string;altText:string;caption:string|null};
export default function MediaPicker({value,onChange,label}:{value:string;onChange:(url:string)=>void;label:string}){
 const [open,setOpen]=useState(false),[items,setItems]=useState<Media[]>([]),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open)fetch('/api/admin/media/library').then(r=>r.json()).then(data=>{if(Array.isArray(data))setItems(data)}).catch(()=>setError('Could not load media.'))},[open]);
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=e.currentTarget;try{const r=await fetch('/api/admin/media',{method:'POST',body:new FormData(form)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Upload failed');onChange(data.url);setOpen(false);form.reset()}catch(e){setError(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}}
 return <div className="field full"><label>{label}</label>{value&&<div className="media-preview"><Image src={value} alt="Selected media" width={130} height={100} unoptimized/><button type="button" className="text-link" onClick={()=>onChange('')}>Remove</button></div>}<button type="button" className="button button-outline" onClick={()=>setOpen(!open)}>{value?'Replace image':'Choose or upload image'}</button>{open&&<div className="media-picker"><input className="search-input" placeholder="Search your media" aria-label="Search media" value={search} onChange={e=>setSearch(e.target.value)}/><div className="media-grid">{items.filter(item=>`${item.altText} ${item.caption||''}`.toLowerCase().includes(search.toLowerCase())).map(item=><button type="button" key={item.id} onClick={()=>{onChange(item.url);setOpen(false)}}><Image src={item.url} alt={item.altText} width={160} height={110} unoptimized/><span>{item.altText}</span></button>)}</div>{!items.length&&<p className="muted">Your library is empty. Upload an image below.</p>}<form onSubmit={upload} className="form-grid"><div className="field"><label>New image</label><input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif" required/></div><div className="field"><label>Alt text</label><input name="altText" required placeholder="Describe the image"/></div><button className="button button-dark" disabled={busy}>{busy?'Uploading…':'Upload and select'}</button></form>{error&&<p role="alert" className="notice">{error}</p>}</div>}</div>
}
