import { notFound } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { zone as businessTimeZone } from '@/lib/booking';
import Manager from './manager';
const sections=['calendar','appointments','services','options','categories','artists','team','clients','gallery','social','testimonials','content','policies','faqs','inquiries','notifications','analytics','settings','media'];
export default async function AdminSection({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<{q?:string;page?:string;view?:string}>}){const {section}=await params;const q=await searchParams;if(!sections.includes(section))notFound();const user=await requireUser(['OWNER','ADMIN','ARTIST']);if(user.role==='ARTIST'&&!['calendar','appointments','services','gallery','artists'].includes(section))notFound();const page=Math.max(1,Number(q.page)||1),take=20,skip=(page-1)*take;let records:unknown[]=[];let total=0;const extra:Record<string,unknown>={};const own=user.role==='ARTIST'?user.artist?.id:undefined;
  switch(section){
    case 'team':if(user.role!=='OWNER')notFound();[records,total,extra.artists]=await Promise.all([db.user.findMany({select:{id:true,email:true,role:true,verifiedAt:true,artists:{select:{id:true,displayName:true}}},skip,take}),db.user.count(),db.artist.findMany({select:{id:true,displayName:true}})]);break;
    case 'services':{const where={name:{contains:q.q||'',mode:'insensitive' as const},...(own?{artists:{some:{artistId:own}}}:{})};[records,total,extra.categories,extra.artists]=await Promise.all([db.service.findMany({where,include:{category:true,artists:{include:{artist:true}}},orderBy:{displayOrder:'asc'},skip,take}),db.service.count({where}),db.category.findMany({orderBy:{displayOrder:'asc'}}),db.artist.findMany({where:own?{id:own}:{active:true}})]);break}
    case 'options':[records,total,extra.services]=await Promise.all([db.serviceOption.findMany({include:{service:true},orderBy:{displayOrder:'asc'},skip,take}),db.serviceOption.count(),db.service.findMany({select:{id:true,name:true}})]);break;
    case 'categories':[records,total]=await Promise.all([db.category.findMany({orderBy:{displayOrder:'asc'},skip,take}),db.category.count()]);break;
    case 'artists':[records,total]=await Promise.all([db.artist.findMany({where:own?{id:own}:{},orderBy:{displayOrder:'asc'},skip,take}),db.artist.count({where:own?{id:own}:{}})]);break;
    case 'appointments':{const where={...(own?{artistId:own}:{}),...(q.q?{OR:[{reference:{contains:q.q,mode:'insensitive' as const}},{client:{name:{contains:q.q,mode:'insensitive' as const}}}]}:{})};[records,total]=await Promise.all([db.appointment.findMany({where,include:{client:true,artist:true,service:true,history:{orderBy:{createdAt:'desc'}},payments:true,policyVersion:true},orderBy:{startAt:'desc'},skip,take}),db.appointment.count({where})]);break}
    case 'clients':{const where=q.q?{OR:[{name:{contains:q.q,mode:'insensitive' as const}},{email:{contains:q.q,mode:'insensitive' as const}}]}:{};[records,total]=await Promise.all([db.client.findMany({where,orderBy:{createdAt:'desc'},skip,take}),db.client.count({where})]);break}
    case 'gallery':[records,total,extra.categories,extra.artists,extra.services]=await Promise.all([db.galleryItem.findMany({where:own?{artistId:own}:{},include:{artist:true,category:true,service:true},orderBy:{displayOrder:'asc'},skip,take}),db.galleryItem.count({where:own?{artistId:own}:{}}),db.category.findMany(),db.artist.findMany({where:own?{id:own}:{}}),db.service.findMany({where:own?{artists:{some:{artistId:own}}}:{}})]);break;
    case 'social':[records,total]=await Promise.all([db.socialPost.findMany({orderBy:{displayOrder:'asc'},skip,take}),db.socialPost.count()]);break;
    case 'testimonials':[records,total,extra.artists,extra.services]=await Promise.all([db.testimonial.findMany({orderBy:{createdAt:'desc'},skip,take}),db.testimonial.count(),db.artist.findMany({select:{id:true,displayName:true}}),db.service.findMany({select:{id:true,name:true}})]);break;
    case 'content':[records,total]=await Promise.all([db.contentBlock.findMany({orderBy:{key:'asc'},skip,take}),db.contentBlock.count()]);break;
    case 'policies':[records,total]=await Promise.all([db.policy.findMany({include:{versions:{orderBy:{version:'desc'},take:1}},orderBy:{displayOrder:'asc'},skip,take}),db.policy.count()]);break;
    case 'faqs':[records,total]=await Promise.all([db.fAQ.findMany({orderBy:{displayOrder:'asc'},skip,take}),db.fAQ.count()]);break;
    case 'inquiries':[records,total]=await Promise.all([db.inquiry.findMany({orderBy:{createdAt:'desc'},skip,take}),db.inquiry.count()]);break;
    case 'notifications':[records,total]=await Promise.all([db.notificationTemplate.findMany({skip,take}),db.notificationTemplate.count()]);extra.emailConfigured=!!process.env.RESEND_API_KEY&&!!process.env.EMAIL_FROM;break;
    case 'settings':[records,total]=await Promise.all([db.siteSetting.findMany({skip,take}),db.siteSetting.count()]);break;
    case 'media':[records,total]=await Promise.all([db.media.findMany({orderBy:{createdAt:'desc'},skip,take}),db.media.count()]);break;
    case 'calendar':records=await db.appointment.findMany({where:{...(own?{artistId:own}:{}),startAt:{gte:new Date(Date.now()-30*86400000),lte:new Date(Date.now()+365*86400000)}},include:{client:true,artist:true,service:true},orderBy:{startAt:'asc'},take:1000});total=records.length;extra.artists=await db.artist.findMany({where:own?{id:own}:{active:true}});extra.availability=await db.availability.findMany({where:own?{artistId:own}:{},orderBy:[{weekday:'asc'},{startMinute:'asc'}],take:500});extra.blockedTimes=await db.blockedTime.findMany({where:{...(own?{artistId:own}:{}),endAt:{gte:new Date()}},orderBy:{startAt:'asc'},take:200});break;
    case 'analytics':{const since=new Date(Date.now()-30*86400000);const events=await db.analyticsEvent.groupBy({by:['name'],where:{createdAt:{gte:since}},_count:{name:true}});records=events.sort((a,b)=>b._count.name-a._count.name).slice(0,20);extra.payments=await db.payment.aggregate({where:{status:'paid',createdAt:{gte:since}},_sum:{amount:true}});break}
  }
  return <><div className="admin-toolbar"><div><p className="eyebrow">MahLovely operations</p><h1 style={{fontSize:'3rem',textTransform:'capitalize'}}>{section}.</h1></div></div><Manager section={section} records={JSON.parse(JSON.stringify(records))} total={total} page={page} query={q.q||''} extra={JSON.parse(JSON.stringify(extra))} role={user.role} timeZone={businessTimeZone} initialView={q.view}/></>}
