'use client';
import { useState } from 'react';
type Range={id:string;artistId:string;weekday:number;date:string|null;startMinute:number;endMinute:number};
type Artist={id:string;displayName:string};
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const clock=(minutes:number)=>{const hour=Math.floor(minutes/60),minute=minutes%60;return `${hour%12||12}:${String(minute).padStart(2,'0')} ${hour<12?'AM':'PM'}`};
export default function ScheduleView({ranges,artists,onEdit,onAdd,onRefresh}:{ranges:Range[];artists:Artist[];onEdit:(r:Range)=>void;onAdd:(artistId:string,weekday:number)=>void;onRefresh:()=>void}){const [artist,setArtist]=useState(artists[0]?.id||''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const regular=ranges.filter(r=>r.artistId===artist&&!r.date);const special=ranges.filter(r=>r.artistId===artist&&r.date);
 async function remove(rows:Range[]){if(!rows.length||!confirm(`Mark ${days[rows[0].weekday]} unavailable and remove ${rows.length} time range${rows.length===1?'':'s'}?`))return;setBusy(true);try{for(const row of rows){const r=await fetch('/api/admin/availability',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});if(!r.ok)throw new Error((await r.json()).error||'Could not update hours')}setMessage('Hours updated.');onRefresh()}catch(e){setMessage(e instanceof Error?e.message:'Could not update hours')}finally{setBusy(false)}}
 async function copyMonday(){const monday=regular.filter(r=>r.weekday===1);if(!monday.length){setMessage('Add Monday hours first.');return}if(!confirm('Copy Monday hours to empty weekdays? Existing hours stay as they are.'))return;setBusy(true);try{for(const weekday of [2,3,4,5]){if(regular.some(r=>r.weekday===weekday))continue;for(const row of monday){const response=await fetch('/api/admin/availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:{artistId:artist,weekday,startMinute:row.startMinute,endMinute:row.endMinute}})});if(!response.ok)throw new Error((await response.json()).error||'Could not copy hours')}}setMessage('Monday hours copied to empty weekdays.');onRefresh()}catch(e){setMessage(e instanceof Error?e.message:'Could not copy hours')}finally{setBusy(false)}}
 return <div className="admin-panel"><div className="admin-toolbar"><div><p className="eyebrow">Regular schedule</p><h2>Weekly hours</h2></div><label className="field">Artist<select value={artist} onChange={e=>setArtist(e.target.value)}>{artists.map(a=><option value={a.id} key={a.id}>{a.displayName}</option>)}</select></label></div><div className="schedule-grid">{days.map((day,weekday)=>{const rows=regular.filter(r=>r.weekday===weekday);return <div className="schedule-day" key={day}><strong>{day}</strong><div>{rows.length?rows.map(row=><button className="schedule-range" key={row.id} onClick={()=>onEdit(row)}>{clock(row.startMinute)} to {clock(row.endMinute)} · Edit</button>):<span className="muted">Unavailable</span>}</div><div><button className="text-link" disabled={busy||!artist} onClick={()=>onAdd(artist,weekday)}>{rows.length?'Add hours':'Set hours'}</button>{rows.length>0&&<button className="text-link" disabled={busy} onClick={()=>remove(rows)}>Unavailable</button>}</div></div>})}</div><button className="button button-outline" disabled={busy||!artist} onClick={copyMonday}>Copy Monday to empty weekdays</button>{message&&<p className="notice" role="status">{message}</p>}<h3>Special dates</h3><p className="muted">These hours replace regular hours on the selected date.</p>{special.length?special.map(row=><div className="list-row" key={row.id}><span>{row.date}: {clock(row.startMinute)} to {clock(row.endMinute)}</span><button className="text-link" onClick={()=>onEdit(row)}>Edit</button></div>):<p className="muted">No special hours set.</p>}</div>}
