import { NextRequest,NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { mkdir,writeFile } from 'fs/promises';
import path from 'path';
import sharp from 'sharp';
import { S3Client,PutObjectCommand } from '@aws-sdk/client-s3';
import { currentUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { errorResponse,safeOrigin } from '@/lib/http';
export async function POST(req:NextRequest){if(!safeOrigin(req))return errorResponse('Invalid origin',403);const user=await currentUser();if(!user||!['OWNER','ADMIN','ARTIST'].includes(user.role))return errorResponse('Forbidden',403);try{const data=await req.formData();const file=data.get('file'),altText=String(data.get('altText')||'').trim(),caption=String(data.get('caption')||'').trim();if(!(file instanceof File)||!altText)return errorResponse('Image and alt text required');if(file.size>10*1024*1024)return errorResponse('Image must be under 10 MB');if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type))return errorResponse('Unsupported image type');const input=Buffer.from(await file.arrayBuffer());const metadata=await sharp(input).metadata();if(!metadata.width||!metadata.height||metadata.width>10000||metadata.height>10000)return errorResponse('Invalid image');const output=await sharp(input).rotate().resize({width:1800,height:1800,fit:'inside',withoutEnlargement:true}).webp({quality:82}).toBuffer();const filename=`${randomUUID()}.webp`;let url:string;if(process.env.S3_BUCKET&&process.env.S3_REGION&&process.env.S3_PUBLIC_URL){const client=new S3Client({region:process.env.S3_REGION});await client.send(new PutObjectCommand({Bucket:process.env.S3_BUCKET,Key:`media/${filename}`,Body:output,ContentType:'image/webp',CacheControl:'public,max-age=31536000,immutable'}));url=`${process.env.S3_PUBLIC_URL.replace(/\/$/,'')}/media/${filename}`}else if(process.env.NODE_ENV!=='production'){const directory=path.join(process.cwd(),'public','uploads');await mkdir(directory,{recursive:true});await writeFile(path.join(directory,filename),output);url=`/uploads/${filename}`}else return errorResponse('Object storage is not configured',503);const media=await db.media.create({data:{url,mimeType:'image/webp',size:output.length,width:Math.min(metadata.width,1800),height:Math.min(metadata.height,1800),altText,caption:caption||null}});await db.auditLog.create({data:{actorId:user.id,action:'upload',entity:'media',entityId:media.id}});return NextResponse.json({id:media.id,url})}catch{return errorResponse('Upload failed',503)}}
