'use client';
import { useEffect,useState } from 'react';
export default function AccountActions({id,reference,serviceId,artistId,canCancel,canReschedule}:{id:string;reference:string;serviceId:string;artistId:string;canCancel:boolean;canReschedule:boolean}){
  const [message,setMessage]=useState(''),[show,setShow]=useState(false),[date,setDate]=useState(''),[time,setTime]=useState(''),[slots,setSlots]=useState<string[]>([]),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!date||!show)return;let active=true;fetch(`/api/slots?serviceId=${encodeURIComponent(serviceId)}&artistId=${encodeURIComponent(artistId)}&date=${date}`).then(r=>r.json()).then(data=>{if(active)setSlots(data.slots||[])}).catch(()=>{if(active)setSlots([])});return()=>{active=false}},[date,show,serviceId,artistId]);
  async function cancel(){if(!window.confirm('Cancel this appointment?'))return;setBusy(true);const response=await fetch(`/api/appointments/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel'})});const body=await response.json();setMessage(body.error||'Appointment cancelled.');setBusy(false);if(response.ok)window.location.reload()}
  async function reschedule(){if(!date||!time)return setMessage('Choose a date and time.');setBusy(true);const response=await fetch(`/api/appointments/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reschedule',date,time})});const body=await response.json();setMessage(body.error||'Appointment rescheduled.');setBusy(false);if(response.ok)window.location.reload()}
  return <div><div className="actions">{canCancel&&<button className="text-link" disabled={busy} onClick={cancel}>Cancel appointment</button>}{canReschedule?<button className="text-link" onClick={()=>setShow(!show)}>Choose a new time</button>:<a className="text-link" href={`/contact?subject=Reschedule%20${reference}`}>Ask to reschedule ↗</a>}</div>{show&&<div className="stack" style={{maxWidth:420,marginTop:16}}><div className="field"><label htmlFor={`reschedule-${id}`}>New date</label><input id={`reschedule-${id}`} type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>{setDate(e.target.value);setTime('')}}/></div>{date&&<div className="slot-grid">{slots.length?slots.map(slot=><button className={`slot ${time===slot?'selected':''}`} key={slot} onClick={()=>setTime(slot)}>{slot}</button>):<p>No times available on this date.</p>}</div>}<button className="button button-dark" disabled={busy||!time} onClick={reschedule}>Confirm new time</button></div>}{message&&<p role="status" className="notice">{message}</p>}</div>
}
