import type { Metadata } from 'next';
import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import AccountActions from './actions';
import { bookingRules, withinRule } from '@/lib/rules';
export const metadata:Metadata={title:'My Account'};
export default async function Account(){const user=await requireUser();if(user.role==='CLIENT'&&!user.verifiedAt)return <section className="section"><div className="container prose"><h1>Verify your email.</h1><p>Please use the verification link sent to your email before viewing appointment history.</p></div></section>;const rules=await bookingRules();const client=await db.client.findUnique({where:{email:user.email},include:{appointments:{include:{artist:true,service:true},orderBy:{startAt:'desc'},take:30}}});const upcoming=client?.appointments.filter(a=>a.startAt>=new Date()&&a.status!=='CANCELLED')||[];const past=client?.appointments.filter(a=>a.startAt<new Date()||a.status==='CANCELLED')||[];return <><section className="page-hero"><div className="container"><p className="eyebrow">Your MahLovely account</p><h1>Hello{client?.name?`, ${client.name.split(' ')[0]}`:''}.</h1><p>See what is coming up, revisit past appointments, and plan your next visit.</p></div></section><section className="section-tight"><div className="container"><div className="admin-toolbar"><h2 style={{fontSize:'2.5rem'}}>Upcoming appointments</h2><Link className="button button-dark" href="/book">Book again ↗</Link></div>{upcoming.length?<div className="stack">{upcoming.map(a=><article className="service-card" key={a.id}><p className="eyebrow">{a.reference} · {a.status.toLowerCase()}</p><h3>{a.service.name} with {a.artist.displayName}</h3><p>{a.startAt.toLocaleString('en-US',{timeZone:'America/New_York',dateStyle:'full',timeStyle:'short'})}</p><p>Payment: {a.paymentStatus.toLowerCase().replaceAll('_',' ')}</p>{a.service.preparation&&<p><strong>Before your visit:</strong> {a.service.preparation}</p>}<AccountActions id={a.id} reference={a.reference} serviceId={a.serviceId} artistId={a.artistId} canCancel={rules.allowSelfServiceCancel&&withinRule(a.startAt,rules.cancelBeforeHours)} canReschedule={rules.allowSelfServiceReschedule&&withinRule(a.startAt,rules.rescheduleBeforeHours)}/></article>)}</div>:<div className="empty-state"><h3>No upcoming appointments.</h3><p>Ready to plan your next visit?</p><Link className="button button-outline" href="/services">Explore services</Link></div>}<div className="admin-toolbar" style={{marginTop:70}}><h2 style={{fontSize:'2.5rem'}}>Past visits</h2></div>{past.length?<div className="stack">{past.map(a=><article className="list-row" key={a.id}><div><strong>{a.service.name}</strong><p className="muted">{a.artist.displayName} · {a.startAt.toLocaleDateString('en-US',{timeZone:'America/New_York'})} · {a.status.toLowerCase()}</p>{a.service.aftercare&&<p>{a.service.aftercare}</p>}</div><Link className="text-link" href={`/book?service=${a.service.slug}`}>Rebook ↗</Link></article>)}</div>:<p className="muted">Your completed appointments will appear here.</p>}</div></section></>}

